### ISSUE TITLE
Blank preview popup

### ISSUE THREAD

**Issue by junpet** [sismics/docs#363]
I just installed `docs` using Docker. I've to search for a little bit to use with PostgreSQL, but I could manage it. Please improve this section in the `readme.md`. Thanks.

Anyway, my `docker-compose.yml` can be found at the bottom. As you can see I'm using `traefik`. I can connect, log in, upload `.pdf` files, but when I click on one of the preview I got a blank (transparent) [popup](https://user-images.githubusercontent.com/3465278/71540536-492a8c80-294c-11ea-97ee-89b34daa0f4a.png). Well, the `.pdf` is downloaded after clicking the preview. As it mentioned, I set the environment variable `DOCS_BASE_URL`. What am I missing?

Hint: My main browser is the latest Firefox. I've tried with the latest Vivaldi as well, and I got the following text in the [popup](https://user-images.githubusercontent.com/3465278/71540701-46309b80-294e-11ea-96bc-ce5143cc9e97.png): 
```docs.[my domain, but I don't want to share] refused to connect.```
I force `https` instead of `http` with `traefik`. I think `docs` want to show the preview with `http` instead of `https`, and that's why the connection is refused. But this is an amateur guess from me.

Could you help me?

```yml
version: "3.7"

services:
  docs:
    image: sismics/docs:v1.7
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
      - DATABASE_URL=jdbc:postgresql://db:5432/docs
      - DATABASE_USER=docs
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - docs-data:/data
    networks:
      - traefik-network
      - postgres-network
    labels:
      - "traefik.enable=true"
      - "traefik.backend=docs"
      - "traefik.frontend.rule=Host:docs.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-network"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

volumes:
  docs-data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/docs"

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
```

**Comment by jendib** [comment]
Thumbnail URL are relative.

Do you have any errors in the logs when you add a file (this is when the thumbnail is generated)?

**Comment by junpet** [comment]
This is the log when I attempted to add a file to a already existing document:
```
docs    | 2019-12-28T11:27:44.244496422Z 28 Dec 2019 12:27:44,243 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=621b547e-cbd7-4c4a-8a90-616c55cedda5, name=IMG.pdf}, language=eng} 
docs    | 2019-12-28T11:27:44.255853198Z 28 Dec 2019 12:27:44,255 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=7fab5608-c553-4514-a770-be174b7ad4bb} 
docs    | 2019-12-28T11:27:44.508432940Z 28 Dec 2019 12:27:44,507 WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:137) SQL Error: 0, SQLState: 42703 
docs    | 2019-12-28T11:27:44.510263346Z 28 Dec 2019 12:27:44,509 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:142) ERROR: column "d" of relation "t_document" does not exist
docs    | 2019-12-28T11:27:44.510367809Z   Position: 25 
docs    | 2019-12-28T11:27:44.540704144Z 28 Dec 2019 12:27:44,520 ERROR com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:51) An exception occured, rolling back current transaction 
docs    | 2019-12-28T11:27:44.540796516Z javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
docs    | 2019-12-28T11:27:44.540945213Z        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
docs    | 2019-12-28T11:27:44.540981401Z        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
docs    | 2019-12-28T11:27:44.541071383Z        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1604)
docs    | 2019-12-28T11:27:44.541106398Z        at com.sismics.docs.core.dao.DocumentDao.updateFileId(DocumentDao.java:239)
docs    | 2019-12-28T11:27:44.541201759Z        at com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.lambda$on$0(DocumentUpdatedAsyncListener.java:61)
docs    | 2019-12-28T11:27:44.541262285Z        at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
docs    | 2019-12-28T11:27:44.541354792Z        at com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:42)
docs    | 2019-12-28T11:27:44.541392617Z        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docs    | 2019-12-28T11:27:44.541484697Z        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
docs    | 2019-12-28T11:27:44.541518887Z        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docs    | 2019-12-28T11:27:44.541605216Z        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
docs    | 2019-12-28T11:27:44.541639262Z        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
docs    | 2019-12-28T11:27:44.541724757Z        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
docs    | 2019-12-28T11:27:44.541758747Z        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
docs    | 2019-12-28T11:27:44.541850353Z        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
docs    | 2019-12-28T11:27:44.541884520Z        at java.base/java.lang.Thread.run(Thread.java:834)
docs    | 2019-12-28T11:27:44.541971236Z Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
docs    | 2019-12-28T11:27:44.542004504Z        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
docs    | 2019-12-28T11:27:44.542090935Z        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
docs    | 2019-12-28T11:27:44.542128818Z        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
docs    | 2019-12-28T11:27:44.542217323Z        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
docs    | 2019-12-28T11:27:44.542250928Z        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
docs    | 2019-12-28T11:27:44.542354721Z        at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
docs    | 2019-12-28T11:27:44.542388138Z        at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1593)
docs    | 2019-12-28T11:27:44.542475957Z        at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:292)
docs    | 2019-12-28T11:27:44.542509441Z        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1594)
docs    | 2019-12-28T11:27:44.542593694Z        ... 13 more
docs    | 2019-12-28T11:27:44.542626768Z Caused by: org.postgresql.util.PSQLException: ERROR: column "d" of relation "t_document" does not exist
docs    | 2019-12-28T11:27:44.542735397Z   Position: 25
docs    | 2019-12-28T11:27:44.542769828Z        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
docs    | 2019-12-28T11:27:44.542851023Z        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
docs    | 2019-12-28T11:27:44.542911053Z        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
docs    | 2019-12-28T11:27:44.543002972Z        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
docs    | 2019-12-28T11:27:44.543036869Z        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
docs    | 2019-12-28T11:27:44.543122979Z        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
docs    | 2019-12-28T11:27:44.543156665Z        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
docs    | 2019-12-28T11:27:44.543241220Z        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
docs    | 2019-12-28T11:27:44.543274111Z        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
docs    | 2019-12-28T11:27:44.543358898Z        ... 17 more
docs    | 2019-12-28T11:27:44.702174539Z 28 Dec 2019 12:27:44,701 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 7 classes for FormatHandler 
docs    | 2019-12-28T11:27:46.228597271Z 28 Dec 2019 12:27:46,227 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 97ms
```

**Comment by jendib** [comment]
It seems you have a broken database, maybe an configuration/installation issue. You can try with a blank database to be sure.

**Comment by junpet** [comment]
I dropped and recreated the database, but the same error occurs.

This is the log while the app starts. There are some warnings.
```
docs    | 2019-12-28T12:22:29.824209595Z Running Jetty: 
docs    | 2019-12-28T12:22:30.942383328Z 2019-12-28 13:22:30.938:INFO::main: Logging initialized @1101ms to org.eclipse.jetty.util.log.StdErrLog
docs    | 2019-12-28T12:22:31.315961890Z 2019-12-28 13:22:31.315:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
docs    | 2019-12-28T12:22:31.432471777Z 2019-12-28 13:22:31.432:INFO:oejs.Server:main: jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 11.0.2+9-Ubuntu-3ubuntu118.04.3
docs    | 2019-12-28T12:22:31.453917510Z 2019-12-28 13:22:31.453:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty/webapps/] at interval 1
docs    | 2019-12-28T12:22:34.752482930Z 2019-12-28 13:22:34.752:WARN:oeja.AnnotationParser:main: Unknown asm implementation version, assuming version 393216
docs    | 2019-12-28T12:22:34.917580877Z 2019-12-28 13:22:34.917:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=162ms
docs    | 2019-12-28T12:22:35.400652480Z 2019-12-28 13:22:35.399:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
docs    | 2019-12-28T12:22:35.400997895Z 2019-12-28 13:22:35.400:INFO:oejs.session:main: No SessionScavenger set, using defaults
docs    | 2019-12-28T12:22:35.402457390Z 2019-12-28 13:22:35.402:INFO:oejs.session:main: node0 Scavenging every 600000ms
docs    | 2019-12-28T12:22:35.803804168Z 28 Dec 2019 13:22:35,793 INFO com.sismics.util.filter.RequestContextFilter.init(RequestContextFilter.java:42) Using base data directory: /data 
docs    | 2019-12-28T12:22:35.850273778Z 28 Dec 2019 13:22:35,849 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:84) Configuring EntityManager from environment parameters 
docs    | 2019-12-28T12:22:37.735101087Z 28 Dec 2019 13:22:37,734 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:57) Opening database and executing incremental updates 
docs    | 2019-12-28T12:22:37.745052132Z 28 Dec 2019 13:22:37,744 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:83) Unable to get database version: Table T_CONFIG not found 
docs    | 2019-12-28T12:22:37.747159312Z 28 Dec 2019 13:22:37,746 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:98) Executing initial schema creation script 
docs    | 2019-12-28T12:22:37.760807967Z 28 Dec 2019 13:22:37,760 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-000-0.sql 
docs    | 2019-12-28T12:22:37.906172705Z 28 Dec 2019 13:22:37,905 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:106) Found database version 0, new version is 24, executing database incremental update scripts 
docs    | 2019-12-28T12:22:37.908719430Z 28 Dec 2019 13:22:37,908 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-001-0.sql 
docs    | 2019-12-28T12:22:37.917188438Z 28 Dec 2019 13:22:37,916 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-002-0.sql 
docs    | 2019-12-28T12:22:37.921850691Z 28 Dec 2019 13:22:37,921 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-003-0.sql 
docs    | 2019-12-28T12:22:37.937387801Z 28 Dec 2019 13:22:37,936 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-004-0.sql 
docs    | 2019-12-28T12:22:37.943880365Z 28 Dec 2019 13:22:37,943 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-005-0.sql 
docs    | 2019-12-28T12:22:37.948242338Z 28 Dec 2019 13:22:37,947 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-006-0.sql 
docs    | 2019-12-28T12:22:38.159936068Z 28 Dec 2019 13:22:38,159 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-007-0.sql 
docs    | 2019-12-28T12:22:38.169415537Z 28 Dec 2019 13:22:38,168 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-008-0.sql 
docs    | 2019-12-28T12:22:38.186950733Z 28 Dec 2019 13:22:38,184 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-009-0.sql 
docs    | 2019-12-28T12:22:38.193122808Z 28 Dec 2019 13:22:38,192 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-010-0.sql 
docs    | 2019-12-28T12:22:38.199828155Z 28 Dec 2019 13:22:38,199 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-011-0.sql 
docs    | 2019-12-28T12:22:38.205729106Z 28 Dec 2019 13:22:38,205 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-012-0.sql 
docs    | 2019-12-28T12:22:38.213427435Z 28 Dec 2019 13:22:38,212 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-013-0.sql 
docs    | 2019-12-28T12:22:38.222494763Z 28 Dec 2019 13:22:38,221 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-014-0.sql 
docs    | 2019-12-28T12:22:38.228432410Z 28 Dec 2019 13:22:38,227 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-015-0.sql 
docs    | 2019-12-28T12:22:38.266358589Z 28 Dec 2019 13:22:38,265 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-016-0.sql 
docs    | 2019-12-28T12:22:38.269808568Z 28 Dec 2019 13:22:38,269 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-017-0.sql 
docs    | 2019-12-28T12:22:38.275377902Z 28 Dec 2019 13:22:38,274 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-018-0.sql 
docs    | 2019-12-28T12:22:38.282713732Z 28 Dec 2019 13:22:38,282 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-019-0.sql 
docs    | 2019-12-28T12:22:38.290043919Z 28 Dec 2019 13:22:38,289 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-020-0.sql 
docs    | 2019-12-28T12:22:38.300643522Z 28 Dec 2019 13:22:38,300 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-021-0.sql 
docs    | 2019-12-28T12:22:38.306148772Z 28 Dec 2019 13:22:38,305 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-022-0.sql 
docs    | 2019-12-28T12:22:38.312307244Z 28 Dec 2019 13:22:38,311 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-023-0.sql 
docs    | 2019-12-28T12:22:38.317024180Z 28 Dec 2019 13:22:38,316 INFO com.sismics.util.jpa.DbOpenHelper.executeAllScript(DbOpenHelper.java:142) Executing script: dbupdate-024-0.sql 
docs    | 2019-12-28T12:22:38.338504326Z 28 Dec 2019 13:22:38,337 INFO com.sismics.util.jpa.DbOpenHelper.open(DbOpenHelper.java:108) Database upgrade complete 
docs    | 2019-12-28T12:22:38.346106217Z 28 Dec 2019 13:22:38,345 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:84) Configuring EntityManager from environment parameters 
docs    | 2019-12-28T12:22:42.017345740Z 28 Dec 2019 13:22:42,016 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 1 classes for IndexingHandler 
docs    | 2019-12-28T12:22:42.091146258Z 28 Dec 2019 13:22:42,090 INFO com.sismics.docs.core.util.indexing.LuceneIndexingHandler.initLucene(LuceneIndexingHandler.java:119) Using file Lucene storage: /data/lucene 
docs    | 2019-12-28T12:22:42.385255665Z 28 Dec 2019 13:22:42,383 INFO com.sismics.docs.core.service.FileService.startUp(FileService.java:39) File service starting up 
docs    | 2019-12-28T12:22:42.396933127Z 28 Dec 2019 13:22:42,396 INFO com.sismics.docs.core.service.InboxService.startUp(InboxService.java:49) Inbox service starting up 
docs    | 2019-12-28T12:22:42.569313545Z WARNING: An illegal reflective access operation has occurred
docs    | 2019-12-28T12:22:42.569414927Z WARNING: Illegal reflective access by com.lowagie.text.pdf.MappedRandomAccessFile$1 (file:/tmp/jetty-0.0.0.0-8080-docs.war-_-any-13308477172665828097.dir/webapp/WEB-INF/lib/itext-2.1.7.jar) to method java.nio.DirectByteBuffer.cleaner()
docs    | 2019-12-28T12:22:42.569559891Z WARNING: Please consider reporting this to the maintainers of com.lowagie.text.pdf.MappedRandomAccessFile$1
docs    | 2019-12-28T12:22:42.569594895Z WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
docs    | 2019-12-28T12:22:42.569681533Z WARNING: All illegal access operations will be denied in a future release
docs    | 2019-12-28T12:22:44.151993084Z 2019-12-28 13:22:44.151:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@3c46e67a{Teedy,/,file:///tmp/jetty-0.0.0.0-8080-docs.war-_-any-13308477172665828097.dir/webapp/,AVAILABLE}{/docs.war}
docs    | 2019-12-28T12:22:44.174239542Z 2019-12-28 13:22:44.173:INFO:oejs.AbstractConnector:main: Started ServerConnector@64de9fa4{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
docs    | 2019-12-28T12:22:44.174565683Z 2019-12-28 13:22:44.174:INFO:oejs.Server:main: Started @14338ms
```

I logged in and created a new empty document. There's a warning as well (as I thought, the application want to use `http`).
```
docs    | 2019-12-28T12:24:44.940683487Z 28 Dec 2019 13:24:44,939 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 1 classes for AuthenticationHandler 
docs    | 2019-12-28T12:25:02.707879124Z Dec 28, 2019 1:25:02 PM org.glassfish.jersey.servlet.WebComponent filterFormParameters
docs    | 2019-12-28T12:25:02.707946823Z WARNING: A servlet request to the URI http://docs.mydomain.com/api/document?language=eng&title=Test+document contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
docs    | 2019-12-28T12:25:02.752847465Z 28 Dec 2019 13:25:02,752 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=885a4ad2-feae-4910-a3a3-d6ba037b6ff9}}
```

And once again uploaded a file. I've checked the `t_document` table, and there's no such column `d`.

| Column            | Type                         |
|-------------------|------------------------------|
| doc_id_c          | character varying(36)        |
| doc_iduser_c      | character varying(36)        |
| doc_title_c       | character varying(100)       |
| doc_description_c | character varying(4000) NULL |
| doc_createdate_d  | timestamp NULL               |
| doc_deletedate_d  | timestamp NULL               |
| doc_language_c    | character varying(7) [eng]   |
| doc_subject_c     | character varying(500) NULL  |
| doc_identifier_c  | character varying(500) NULL  |
| doc_publisher_c   | character varying(500) NULL  |
| doc_format_c      | character varying(500) NULL  |
| doc_source_c      | character varying(500) NULL  |
| doc_type_c        | character varying(500) NULL  |
| doc_coverage_c    | character varying(500) NULL  |
| doc_rights_c      | character varying(500) NULL  |
| doc_updatedate_d  | timestamp                    |
| doc_idfile_c      | character varying(36) NULL   |

```
docs    | 2019-12-28T12:25:54.400739337Z 28 Dec 2019 13:25:54,399 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=2c1a8ab7-ee48-43cf-9c07-8dd4cbeeb280, name=IMG.pdf}, language=eng} 
docs    | 2019-12-28T12:25:54.416094317Z 28 Dec 2019 13:25:54,415 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=885a4ad2-feae-4910-a3a3-d6ba037b6ff9} 
docs    | 2019-12-28T12:25:54.472225743Z 28 Dec 2019 13:25:54,471 WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:137) SQL Error: 0, SQLState: 42703 
docs    | 2019-12-28T12:25:54.472516619Z 28 Dec 2019 13:25:54,472 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:142) ERROR: column "d" of relation "t_document" does not exist
docs    | 2019-12-28T12:25:54.472685678Z   Position: 25 
docs    | 2019-12-28T12:25:54.492657575Z 28 Dec 2019 13:25:54,480 ERROR com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:51) An exception occured, rolling back current transaction 
docs    | 2019-12-28T12:25:54.492921799Z javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
docs    | 2019-12-28T12:25:54.493037272Z        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
docs    | 2019-12-28T12:25:54.493144115Z        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
docs    | 2019-12-28T12:25:54.493247355Z        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1604)
docs    | 2019-12-28T12:25:54.493357964Z        at com.sismics.docs.core.dao.DocumentDao.updateFileId(DocumentDao.java:239)
docs    | 2019-12-28T12:25:54.493462135Z        at com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.lambda$on$0(DocumentUpdatedAsyncListener.java:61)
docs    | 2019-12-28T12:25:54.493566002Z        at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
docs    | 2019-12-28T12:25:54.493664958Z        at com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:42)
docs    | 2019-12-28T12:25:54.493764960Z        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docs    | 2019-12-28T12:25:54.493858419Z        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
docs    | 2019-12-28T12:25:54.493904019Z        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
docs    | 2019-12-28T12:25:54.494051166Z        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
docs    | 2019-12-28T12:25:54.494156407Z        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
docs    | 2019-12-28T12:25:54.494262409Z        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
docs    | 2019-12-28T12:25:54.494373434Z        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
docs    | 2019-12-28T12:25:54.494408692Z        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
docs    | 2019-12-28T12:25:54.494575792Z        at java.base/java.lang.Thread.run(Thread.java:834)
docs    | 2019-12-28T12:25:54.494716137Z Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
docs    | 2019-12-28T12:25:54.494828337Z        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
docs    | 2019-12-28T12:25:54.494931960Z        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
docs    | 2019-12-28T12:25:54.494969691Z        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
docs    | 2019-12-28T12:25:54.495106366Z        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
docs    | 2019-12-28T12:25:54.495209158Z        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
docs    | 2019-12-28T12:25:54.495310586Z        at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
docs    | 2019-12-28T12:25:54.495408226Z        at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1593)
docs    | 2019-12-28T12:25:54.495452203Z        at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:292)
docs    | 2019-12-28T12:25:54.495590211Z        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1594)
docs    | 2019-12-28T12:25:54.498821855Z        ... 13 more
docs    | 2019-12-28T12:25:54.499017713Z Caused by: org.postgresql.util.PSQLException: ERROR: column "d" of relation "t_document" does not exist
docs    | 2019-12-28T12:25:54.499055107Z   Position: 25
docs    | 2019-12-28T12:25:54.499143499Z        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
docs    | 2019-12-28T12:25:54.499180740Z        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
docs    | 2019-12-28T12:25:54.499266741Z        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
docs    | 2019-12-28T12:25:54.499301765Z        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
docs    | 2019-12-28T12:25:54.499389004Z        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
docs    | 2019-12-28T12:25:54.499423887Z        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
docs    | 2019-12-28T12:25:54.499508127Z        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
docs    | 2019-12-28T12:25:54.499542292Z        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
docs    | 2019-12-28T12:25:54.499628061Z        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
docs    | 2019-12-28T12:25:54.499661477Z        ... 17 more
docs    | 2019-12-28T12:25:54.757383137Z 28 Dec 2019 13:25:54,756 INFO com.sismics.util.ClasspathScanner.findClasses(ClasspathScanner.java:48) Found 7 classes for FormatHandler 
docs    | 2019-12-28T12:25:56.325709094Z 28 Dec 2019 13:25:56,325 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 94ms
```

**Comment by jendib** [comment]
Maybe it's a PGSql version issue then. We are using 9.6 internally. Which one you use?

**Comment by jendib** [comment]
It was actually a bug. Table aliases are not supported in the set clause by PGSql. Thanks for the report 👍  The fix is committed in the master branch.

**Comment by junpet** [comment]
Version 11.5, but I'm planning to upgrade to version 12.

**Comment by junpet** [comment]
Please see [my edited answer](https://github.com/sismics/docs/issues/363#issuecomment-569414726). I still cannot see the preview in the popup.

**Comment by Jaimy85** [comment]
It is a Firefox setting, set pdf to open with Firefox then it works.

**Comment by junpet** [comment]
If I'm remember correctly I had to play with Traefik headers settings and I managed to make it work. Since then I switched to Traefik v2.0 successfully, everything is working correctly. So it was not a browser setting (I remember I checked multiple different browsers with the same result, like I wrote in my first post).
