### ISSUE TITLE
psql DB exception with a long type

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#451]
Hi,
since rolling out latest commits i get an error which stops to make the instance working normally

journalctl log and docs.log say:

```
10 Sep. 2020 18:20:04,671 ERROR com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:51) An exception occured, rolling back current transaction 
javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute query
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1514)
	at org.hibernate.query.Query.getResultList(Query.java:135)
	at com.sismics.docs.core.dao.FileDao.findAll(FileDao.java:56)
	at com.sismics.docs.core.listener.async.RebuildIndexAsyncListener.lambda$on$1(RebuildIndexAsyncListener.java:61)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.listener.async.RebuildIndexAsyncListener.on(RebuildIndexAsyncListener.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hibernate.exception.DataException: could not execute query
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.loader.Loader.doList(Loader.java:2692)
	at org.hibernate.loader.Loader.doList(Loader.java:2672)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
	at org.hibernate.loader.Loader.list(Loader.java:2501)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1508)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
	... 14 more
Caused by: org.postgresql.util.PSQLException: Unzulässiger Wert für den Typ long : Mahnung
```
from backend the log looks like this

![grafik](https://user-images.githubusercontent.com/5631071/92763174-9132f780-f393-11ea-8031-80072714c6d2.png)

the issue causes to have documents which should a file count but the file view list within the doucment is empty. and i cannot remove those documents because it throws error. i have this issue for multiple documents now

I am running
- docs from commit https://github.com/sismics/docs/commit/3ad0554a7daa47a3c604e520ffe964c3f2140f09
- Ubuntu 20 LTS am64 (kernel 5.4.0-47-generic)
- postgresql 12.4-0
- jetty 9.4.26-1

The previous version i ran before upgrading was https://github.com/sismics/docs/commit/82737e22807860d3ae6118eae3a5ec37241f0544 - this worked fine. i guess some small thing changed or it has to be a version-dependent issue regarding postgresql. i looked into all commits between those versions but i was not able to find the possibly affecting lines of code. 

I have no idea what it could be: I did not find any long data type in sql structure (viewed with Oracle SQL Developer). The error does not occure on other instances with the same rolled out version.

is there some possibility to get some more advanced logging maybe? to see the executed query would allow me to dig deeper. i saw that you added some commits about more intense logging but actually i am not sure how to activate this (if available).

regards, Mario

**Comment by vmario89** [comment]
edit: looking into t_file shows that fil_content_c stopped to be inserted as CLOB data. instead the data is now regular text. that must be the issue

![grafik](https://user-images.githubusercontent.com/5631071/92765931-14554d00-f396-11ea-9e2c-78ad53cc1857.png)

**Comment by jendib** [comment]
Nothing was changed on how we are storing the file content. You didn't update your database version?

**Comment by vmario89** [comment]
hi Benjamin, thanks for your ultra-quick reply!

i did the teedy upgrade while moving to a new server with newer postgresql also - previously it was running Ubuntu 16 bis psql 9.5. but i did this move by creating a fresh database and then dumped the sql file into the new database.

**Comment by jendib** [comment]
It might be the migration from PgSQL 9.5 to 12.4 the problem.
 Do you think you can run your database in the old 9.5 version but with the latest Teedy version?

**Comment by vmario89** [comment]
i guess i made a bad mistake. but luckily previous backups exist. i am trying to to dump the db with pg_dumpall instead pg_dump now because i guess there are some structural issues regarding tables spaces and other default objects. i will post feedback to this soon so hopefully it might help other users having same issue in the future

**Comment by jendib** [comment]
It might also come from this new code :
https://github.com/sismics/docs/commit/520b1431650f055bbd68f388717ac658da8fa5f1#diff-34d45702eea5d42a538d1a95c7f76364L156

I can rollback this, but it would be great if you can do a full test before/after to be sure of the cause (PgSQL version or this).

**Comment by vmario89** [comment]
i will try my best. i did some ugly repairings in the meantime on the recent db because the old one is still dumping its way. that dumpall is really slow when having a lot of DBs at it seems. 

for now i just nulled the fil_content_c cols where length is larger than 6, like this

```
SELECT fil_content_c FROM t_file 
WHERE  LENGTH(fil_content_c) > 6
ORDER BY fil_createdate_d DESC;

UPDATE t_file SET fil_content_c = NULL
WHERE  LENGTH(fil_content_c) > 6;
```

while googling some stuff i found some comments about psql and the lob/text datatype
https://www.baeldung.com/jpa-annotation-postgresql-text-type - maybe its required to advance the content with some annotation
@Lob
@Type(type = "org.hibernate.type.TextType")
but it's just some wild guess

happily for some kind of offtopic: i also found some working function in psql to decode the the existing LOB data. that might be useful for some external queries on the database

```
select
fil_name_c,
convert_from(loread(lo_open(fil_content_c::int, 131072), 999999999), 'UTF8')
from t_file WHERE fil_deletedate_d IS NULL AND fil_content_c IS NOT NULL limit 1;
```

**Comment by vmario89** [comment]
hey,
the exact same behaviour happens with psql 9.5 too :-(  i have to revert my previous statement with the other servers. It occures indeed on all my instances. I rolled out that version ~1 week ago and did some quick testings, where it seemed to work properly but i did not push a lot of files. maybe the problem was hidden some weeks/moths because i think most users will use H2 database. 

my other instances are running psql 10/Ubuntu 18 and behave same like psql 9.5 and psql 12. next time i should check the behaviour more deeply with some test server

**Comment by jendib** [comment]
I pushed the change I was talking about, if you can have a look and tell me if creating/updating a file has the same effect on the database values. (latest Docker image is updated).

**Comment by vmario89** [comment]
Hey again,
thanks! I did a recompile with the latest change (vanilla git clone) and restarted the jetty service, but the exception still occures with no change. 
![grafik](https://user-images.githubusercontent.com/5631071/92791093-a8caaa00-f3ac-11ea-97f7-cd28b17812b6.png)

maybe some other change related to this in https://github.com/sismics/docs/commit/d428e89c305bc7f0605c94262a40fe680dddfda7?

**Comment by jendib** [comment]
You tested with a fresh new file? not the old ones

**Comment by vmario89** [comment]
yes i created a new test document and uploaded some random pdf file :-/

**Comment by jendib** [comment]
Could you test with a fresh 12.4 database ?

**Comment by vmario89** [comment]
hey,

i made some new db without any dumping from backup. just a fresh db with fresh user. and with a new /var/docs folder, so a naked instance. create a new doc and uploaded a file. it was available some seconds until tesseract parsed it. the the column was filled again with data and the issue was caused again. so issue still existent
![grafik](https://user-images.githubusercontent.com/5631071/92809755-331b0a00-f3bd-11ea-9daf-b681de889b66.png)


10.09.20 23:26 | RequestContextFilter | An exception occured, rolling back current transaction
-- | -- | --
10.09.20 23:26 | SqlExceptionHelper | Bad value for type long

**Comment by jendib** [comment]
Thanks for doing all the testing, so there seems to be a real issue with PgSQL. I will have a deeper look in the coming days.

**Comment by vmario89** [comment]
thank you! for sure i will assist you for further testing results

**Comment by vmario89** [comment]
hey again, i did not find a solution yet but working with the instance is hard this way. is there some other option to disable OCR'ing content complety in the meantime?  In the backend there is no option is disable the OCR function at all. would help to debug.

the system behaves TOTALLY weird. i uninstalled tesseract-ocr and tesseract-ocr-deu libtesseract4  libtesseract-dev tesseract-ocr-eng tesseract-ocr-osd packages. The command "tesseract" is now unavailable in system then. on bash "which tesseract" returns nothing. I restarted Jetty multiple times but teedy still generates input which is filled in into the database field fil_content_c. how can this be?

**Comment by vmario89** [comment]
okay another test: with deinstalled tesseract i uploaded some PNG file. that works fine and teedy doesnt do strange things

**Comment by jendib** [comment]
I removed the @Lob annotation on the file content column (I found some people online saying it might be this).
Apparently the "org.hibernate.type.TextType" solution is deprecated and not suggested anymore... (we are on the latest Hibernate version almost).

It's still working as before on H2, can you have a look with PgSQL?

**Comment by vmario89** [comment]
great! i can confirm that teedy works again. 

but why it does? was it some dependency library which got too new in the meantime?

My psql database still gets filled with plaintext instead of data with LOB style but teedy handles it correctly now - no crashes in the log.  except some warning about "13.09.20 20:09 | CmapSubtable | Format 14 cmap table is not supported and will be ignored"

**But** the change it has one caveat as negative side effect: all previously OCR processed file seem to require to be reprocessed because the full text search only returns detailed result for fresh upload, but not the existing data. for me it is not the problem because i made some re-processing batch shell script to perform this (https://wiki.fablabchemnitz.de/pages/viewpage.action?pageId=49905700)

**Comment by jendib** [comment]
I updated Hibernate (the ORM) 2 years ago, so it's probably not this.
I really don't see any recent change which could be related to this honestly... and storing the data in plaintext is probably a better idea than in LOB format. Modern database know how to handle this kind of big column.

The need to reprocess is a bit disappointing however, I would have preferred it to be seamless.
Maybe there is a way to convert old data in new format using your SQL query above. Do you think you could give me a database dump (pg_dump format) containing both old and new formats?

The warning is in PDFBox (the library to read PDF files), so it's unrelated (and probably OK).

**Comment by vmario89** [comment]
hey,
i made some conversion psql script. worked the less or more stable for all instances. Maybe you or someone can validate and stabilize this. i invested ~3 hours in this right now.

```
/*
Show items which start with useless linefeeds. We need to correct those because otherwise we cannot continue with following statements (casting "fil_content_c::int" will fail and other issues)
Result may be empty
*/
SELECT
    fil_id_c,
    fil_name_c,
    fil_content_c
FROM t_file
WHERE
	fil_content_c LIKE E'%\n'
;

/*Trim beginning linefeeds (only) away*/
UPDATE t_file SET fil_content_c = TRIM(e'\n' FROM fil_content_c)
WHERE
	fil_content_c LIKE E'%\n'
;

/*
Show faulty data which would return "invalid byte sequence for encoding "UTF8": 0x00" or similar.
First we build some function to check for valid UTF8 bytea because sometimes we have faulty stuff inside DB
Result may be empty
*/
CREATE FUNCTION is_valid_utf8(bytea) RETURNS boolean
   LANGUAGE plpgsql AS
$$BEGIN
   PERFORM convert_from($1, 'UTF8');
   RETURN TRUE;
EXCEPTION
   WHEN character_not_in_repertoire THEN
      RAISE WARNING '%', SQLERRM;
      RETURN FALSE;
END;$$;
SELECT
    fil_id_c,
	fil_name_c,
	loread(lo_open(fil_content_c::int, CAST( x'20000' AS integer)), 999999999) AS BYTE_DATA,
	LENGTH(loread(lo_open(fil_content_c::int, CAST(x'20000' AS integer)), 999999999)) AS LEN
FROM t_file 
WHERE
    fil_content_c IS NOT NULL AND
    fil_content_c != '' AND
    LENGTH(fil_content_c) <= 6 AND
	is_valid_utf8(fil_content_c::bytea) IS FALSE
;

/*We set NULL to all items with faulty UTF-8 encoding (if there were some from previous statement)*/
UPDATE t_file SET fil_content_c = NULL
WHERE  
    fil_content_c IS NOT NULL AND
    fil_content_c != '' AND
    LENGTH(fil_content_c) <= 6 AND
    is_valid_utf8(fil_content_c::bytea) IS FALSE
;

/*
Select OCR content which is in LOB format (Large Object) and valid UTF-8
*/
SELECT
    fil_id_c,
	fil_name_c,
	fil_content_c,
    fil_content_c::bytea, /*shows "invisible" data which does not trigger NULL or ''*/
	loread(lo_open(fil_content_c::int, CAST( x'20000' AS integer)), 999999999) AS BYTE_DATA,
	 /*we use the encoding we used to create the database. See setup instructions. Usually this is "UNICODE" or "UTF8"*/
	LENGTH(loread(lo_open(fil_content_c::int, CAST(x'20000' AS integer)), 999999999)) AS LEN,
	convert_from(loread(lo_open(fil_content_c::int, CAST(x'20000' AS integer)), 999999999), 'UNICODE') as "fil_content_c"
FROM t_file 
WHERE
    fil_content_c IS NOT NULL AND
    fil_content_c != '' AND
    LENGTH(fil_content_c) <= 6 AND
    is_valid_utf8(fil_content_c::bytea) IS TRUE
ORDER BY LEN ASC
;

/*Convert LOB data into plain text. First we do it for a custom selected file with fil_id_c*/
UPDATE t_file SET fil_content_c = convert_from(loread(lo_open(fil_content_c::int, CAST( x'20000' AS integer)), 999999999), 'UNICODE')::TEXT
WHERE
	fil_id_c = '13411bb0-12fd-4e25-b483-2e2d18b344ed'
;

/*Check the conversion value*/
SELECT
    fil_id_c,
    fil_name_c,
    fil_content_c
FROM t_file
WHERE
	fil_id_c = '13411bb0-12fd-4e25-b483-2e2d18b344ed'
;

/*
Now we do mass processing for LOB to plain text
DO NOT CONTINUE WITH OTHER STATEMENTS IF THIS ONE FAILS AND CHECK THE UPPER ONES AGAIN
*/
UPDATE t_file SET fil_content_c = convert_from(loread(lo_open(fil_content_c::int, CAST( x'20000' AS integer)), 999999999), 'UNICODE')::TEXT
WHERE
    fil_content_c IS NOT NULL AND
    fil_content_c != '' AND
    LENGTH(fil_content_c) <= 6 AND
    is_valid_utf8(fil_content_c::bytea) IS TRUE
;

/*We fix again useless linefeeds by trimming*/
UPDATE t_file SET fil_content_c = TRIM(e'\n' FROM fil_content_c)
WHERE
	fil_content_c LIKE E'%\n'
;

/*
Now that we converted all the LOB stuff we do mass processing for remaining stuff with length lesser than 6 chars because those OCR values are just crap
WARNING: DO NOT RUN THIS BEFORE CONVERTING BECAUSE YOU WILL OVERWRITE. IF YOU DID YOU WILL NEED TO REPROCESS ALL DOCUMENTS!
*/
UPDATE t_file SET fil_content_c = NULL
WHERE
    fil_content_c IS NOT NULL AND 
    fil_content_c != '' AND
    LENGTH(fil_content_c) <= 6
;

/*Finally we check again the values visually*/
SELECT
    fil_id_c,
    fil_name_c,
    fil_content_c
FROM t_file

/*Finally re-run the indexing from background UI web interface or API to have a good search index again*/
```

**Comment by jendib** [comment]
Wow thanks for all the efforts, it's quite thorough!

If I put the UPDATE query in the automatic migration process for the next version, I can skip the "checking" part (the custom function), because all data should be in LOB format.
So only this query:
```
UPDATE t_file SET fil_content_c = convert_from(loread(lo_open(fil_content_c::int, CAST( x'20000' AS integer)), 999999999), 'UNICODE')::TEXT
WHERE
    fil_content_c IS NOT NULL
```
I just need to make sure it works 100%, I will do some tests on an old database (LOB format).

**Comment by vmario89** [comment]
yep some more tests are good idea. i used it on a database with ~8000 files, another with ~4500 files and two smaller ones. Maybe some large monster for processing would be good to ensure everything is in place

**Comment by terba** [comment]
The lonely sql update solved my issue (#464). I reindexed after the update and the lucene folder size is around the same as it was before. Thanks!
